src_extended/TSeb.Library.Management.RazorPages.Mvc/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;
using TSeb.Library.Management.RazorPages.Mvc.Models;
using TSeb.Library.Management.RazorPages.Mvc.ViewModels;
using TSeb.Library.Shared.Services;

namespace TSeb.Library.Management.RazorPages.Mvc.Controllers
{
    public class BooksController : Controller
    {
        private readonly IWebHostEnvironment _hostEnv;
        private HttpClient _httpClient;

        public BooksController(IHttpClientFactory httpClientFactory, IWebHostEnvironment hostEnvironment)
        {
            _httpClient = httpClientFactory.CreateClient();
            _hostEnv = hostEnvironment;
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View(new BookVm());
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(BookVm book)
        {
            var books = await ApiHelper.GetDataFromAsync<List<TrackItemModel>>(url: "http://localhost:5000/api/books");

            var data = new TrackItemModel
            {
                Id = books.model.Count + 1, 
                StockQuantity = 1,
                Authors = book.Authors,
                ISBN = book.ISBN,
                Thumbnail = $"{_hostEnv.WebRootPath}/img/{Path.GetFileNameWithoutExtension(book.Thumbnail.FileName)}.jpg",
                Title = book.Title                 
            };
            var json = Newtonsoft.Json.JsonConvert.SerializeObject(data);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            // Create the HttpRequestMessage with the desired URL and HTTP method
            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/api/books"){ Content = content };

            // Send the request and retrieve the response
            HttpResponseMessage response = await _httpClient.SendAsync(request);

            return RedirectToAction("Index", "Home");
        }

        [Route("Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var book = await ApiHelper.GetDataFromAsync<TrackItemModel>(url: $"http://localhost:5000/api/books/{id}");

            var bookVm = new BookVm_Details
            {
                Title = book.model.Title,
                Authors = book.model.Authors,
                BookId = book.model.Id,
                ISBN = book.model.ISBN,
                Thumbnail = book.model.Thumbnail,
                StockQuantity = book.model.StockQuantity
            };

            return View(bookVm);
        }
    }
}

src_extended/TSeb.Library.Management.RazorPages.Mvc/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using TSeb.Library.Management.RazorPages.Mvc.Models;
using TSeb.Library.Management.RazorPages.Mvc.ViewModels;

namespace TSeb.Library.Management.RazorPages.Mvc.Controllers
{
    public class RentalsController : Controller
    {

        private readonly HttpClient _httpClient;

        public RentalsController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient("LibraryManagement.Api");
        }

        [HttpGet]
        public async Task<IActionResult> Rent(int id)
        {
            // Create the HttpRequestMessage with the desired URL and HTTP method
            var request = new HttpRequestMessage(HttpMethod.Get, $"api/books/{id}");

            // Send the request and retrieve the response
            HttpResponseMessage response = await _httpClient.SendAsync(request);
            string responseContent = await response.Content.ReadAsStringAsync();
            var result = JsonConvert.DeserializeObject<TrackItemModel>(responseContent);

            return View(new RentalViewModel { Rental = new RentalModel { Item = result } });
        }

        [HttpPost]
        public async Task<IActionResult> Rent(PostRentViewModel postRentalViewModel)
        {
            var json = JsonConvert.SerializeObject(postRentalViewModel);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            // Create the HttpRequestMessage with the desired URL and HTTP method
            var request = new HttpRequestMessage(HttpMethod.Post, "api/rentals")
            {
                Content = content // Set the content of the request
            };

            // Send the request and retrieve the response
            HttpResponseMessage response = await _httpClient.SendAsync(request);

            return RedirectToAction(nameof(Index), "Home");

        }

        [Route("returned/{id}")]
        public async Task<IActionResult> Returned(int id)
        {
            var request = new HttpRequestMessage(HttpMethod.Delete, $"api/rentals/{id}");
            request.Content = new StringContent(JsonConvert.SerializeObject(new { id }), Encoding.UTF8, "application/json");
            await this._httpClient.SendAsync(request);

            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

src_extended/TSeb.Library.Management.RazorPages.Mvc/Views/Books/Create.cshtml
@using TSeb.Library.Management.RazorPages.Mvc.Models;
@model BookVm

<div class="container">
    <!--Create employee form. To suport file upload we need to use: enctype="multipart/form-data"-->
    <form enctype="multipart/form-data" asp-controller="Books" asp-action="Create" method="post" class="mt-3">

        <!--Name-->
        <div class="form-group row m-1">
            <label class="col-sm-2 col-form-label" asp-for="@Model.Title"></label>
            <div class="col-sm-10">
                <input asp-for="@Model.Title" class="form-control" placeholder="Name" />
                <span class="text-danger" asp-validation-for="@Model.Title"></span>
            </div>
        </div>

        <div class="form-group row m-1">
            <label class="col-sm-2 col-form-label" asp-for="@Model.Authors">Author(s)</label>
            <div class="col-sm-10">
                <input asp-for="@Model.Authors" class="form-control" placeholder="Author" />
                <span class="text-danger" asp-validation-for="@Model.Authors"></span>
            </div>
        </div>

        <div class="form-group row m-1">
            <label class="col-sm-2 col-form-label" asp-for="@Model.ISBN">ISBN</label>
            <div class="col-sm-10">
                <input asp-for="@Model.ISBN" class="form-control" placeholder="ISBN" />
                <span class="text-danger" asp-validation-for="@Model.ISBN"></span>
            </div>
        </div>

        <!--CHOOSE ANOTHER PROFILE PHOTO-->
        <div class="form-group row m-1">
            <label class="col-sm-2 col-form-label" asp-for="@Model.Thumbnail">Thumbnail</label>
            <div class="col-sm-10">
                <div class="custom-file">
                    <input asp-for="@Model.Thumbnail" class="form-control custom-file-input" placeholder="Select a profile photo" />
                </div>
            </div>
        </div>

        <!--PROFILE PHOTO-->
        <div class="form-group row col-sm-4 offset-4 m-1">

            <div class="row">
                <!--NEW PHOTO-->

                <div class="col ">

                    <h6>Thumbnail</h6>
                    <div id="imgPreview" class="thumbnail rounded border" style="display:flex; justify-content:center;">
                        <img class="card-img-top imageThumbnail rounded" id="targetImg" asp-append-version="true" />
                    </div>

                </div>
            </div>
        </div>


        <!--Create button-->
        <div class="form-group row m-1">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>

        @section CustomScripts {

            <script src="~/lib/jquery/jquery.js"></script>

            <!--This will change the text in PhotoPath to the name of the photo-->
            <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(fileName);

                        var File = this.files;
                        if (File && File[0]) {
                            ReadImage(File[0]);
                        }
                    });
                });
            </script>

            <script>
                var ReadImage = function (file) {
                    var reader = new FileReader;
                    var image = new Image;

                    reader.readAsDataURL(file);
                    reader.onload = function (_file) {

                        image.src = _file.target.result;
                        image.onload = function () {

                            $("#targetImg").attr('src', _file.target.result);
                            $("#imgPreview").show();
                        }
                    }
                }
            </script>
        }

    </form>
</div>

src_extended/TSeb.Library.Management.RazorPages.Mvc/Views/Books/Details.cshtml
@model BookVm_Details

<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.Title</h1>
                @foreach (var author in Model.Authors)
                {
                    <p>@author</p>
                }
              
            </div>

            <div class="card-body text-center">
                <!--asp-append-version="true" serves as Reloading the image only if it changes on the server.
                If it's not being changed, take it from webcache-->
                <img class="card-img-top imageThumbnail rounded mx-auto"
                     src=@Model.Thumbnail
                     asp-append-version="true" />

                <h5>Book ISBN: @Model.ISBN</h5>
            </div>

            <div class="card-footer text-center">

                <!--Back to Home index-->
                <a asp-controller="Home" asp-action="index" class="btn btn-primary m-1">Back</a>
                @if(Model.StockQuantity > 0){
                    <a class="btn btn-primary m-1" asp-controller="Rentals" asp-action="Rent"
                       asp-route-id="@Model.BookId">Rent</a>
                }
            </div>
        </div>
    </div>
</div>